{{- if .Values.cache.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hiresphere.componentFullname" (dict "root" . "component" "redis") }}
  labels:
    {{- include "hiresphere.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hiresphere.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "hiresphere.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 999
      containers:
        - name: redis
          image: {{ printf "%s:%s" .Values.cache.image.repository .Values.cache.image.tag | quote }}
          imagePullPolicy: {{ .Values.cache.image.pullPolicy }}
          command: ["redis-server", "--save", "", "--appendonly", "no"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 999
            runAsGroup: 999
          ports:
            - name: redis
              containerPort: {{ .Values.cache.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.cache.resources | nindent 12 }}
{{- end }}
