{{- if and .Values.database.enabled (not .Values.database.auth.existingSecret) }}
{{- $secretName := include "hiresphere.databaseSecretName" . }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $postgresPassword := randAlphaNum 32 }}
{{- if and $existingSecret (hasKey $existingSecret.data "postgres-password") }}
{{- $postgresPassword = (index $existingSecret.data "postgres-password" | b64dec) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "hiresphere.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
stringData:
  postgres-database: {{ .Values.database.auth.postgresDatabase | quote }}
  postgres-username: {{ .Values.database.auth.postgresUsername | quote }}
  postgres-password: {{ default $postgresPassword .Values.database.auth.postgresPassword | quote }}
{{- end }}
