{{- if and .Values.api.enabled (eq .Values.storage.provider "s3") (not .Values.storage.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hiresphere.storageSecretName" . }}
  labels:
    {{- include "hiresphere.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
type: Opaque
stringData:
  aws-access-key-id: {{ .Values.storage.s3.accessKeyId | quote }}
  aws-secret-access-key: {{ .Values.storage.s3.secretAccessKey | quote }}
{{- end }}
